// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzanteyeatulryrnewzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6YW50ZXllYXR1bHJ5cm5ld3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDY2MDgsImV4cCI6MjA2ODgyMjYwOH0.bHaoCVsF5pXSQuWcaRsIqcCmYKgKEr-LTd103oZksOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});